// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWcUzX4gmKc2bhTD9filHuDU3d14ZI-Fg',
    appId: '1:861554206593:web:599c92a79854208b97ea80',
    messagingSenderId: '861554206593',
    projectId: 'crud-flutter-9704f',
    authDomain: 'crud-flutter-9704f.firebaseapp.com',
    storageBucket: 'crud-flutter-9704f.appspot.com',
    measurementId: 'G-WD48R511RK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYQ44VlHEGbsjR9CHWosrdYFgiJVOp3i4',
    appId: '1:861554206593:android:97efcb726c08d1d597ea80',
    messagingSenderId: '861554206593',
    projectId: 'crud-flutter-9704f',
    storageBucket: 'crud-flutter-9704f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuEmF4ift1CvPqZl9W80RJoloUaDwBqd0',
    appId: '1:861554206593:ios:f3ebdceba34a1d6d97ea80',
    messagingSenderId: '861554206593',
    projectId: 'crud-flutter-9704f',
    storageBucket: 'crud-flutter-9704f.appspot.com',
    iosBundleId: 'com.example.crudOperation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuEmF4ift1CvPqZl9W80RJoloUaDwBqd0',
    appId: '1:861554206593:ios:6fd645757196e71c97ea80',
    messagingSenderId: '861554206593',
    projectId: 'crud-flutter-9704f',
    storageBucket: 'crud-flutter-9704f.appspot.com',
    iosBundleId: 'com.example.crudOperation.RunnerTests',
  );
}
